name: Release Drafter

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
        # write permission is required to create a github release
        contents: write
        # write permission is required for autolabeler
        # otherwise, read permission is required at least
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Label PR
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "APIBreakingChanges, breakingChanges, newContributors, notableChanges, sdou, skipReleaseNotes, TypeBug, TypeEnhancement, TypeTest"
          add_comment: true
          message: "Label error: This PR is being prevented from merging because you have not added one of the labels: {{ provided }}. You'll need to add it before this PR can be merged."